[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*.html"
    [headers.values]
      Cache-Control = "no-store"

[[headers]]
  for = "/*.js"
    [headers.values]
      Cache-Control = "no-store"
      
      
[[headers]]
  for = "/*.css"
    [headers.values]
      Cache-Control = "no-store"